name: ci-python

on: [push]

jobs:
  checkout-aplication:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Display Python version
        run: pip install pytest
        run: pytest test_calculadora.py