name: ci

on:
  pull_request:
    branches:
      - develop

jobs:
  checkout-aplication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Instalar dependencias
        run: python3 -m pip install pytest
      - name: Executar teste
        run: pytest test_calculadora.py